# Generated by Django 5.1 on 2026-02-04 07:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=200)),
                ('facility', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_observed', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='observations/before/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_VERIFICATION', 'Awaiting Verification'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('rectification_details', models.TextField(blank=True)),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='observations/after/')),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('verification_comment', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_observations', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observations.location')),
                ('observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.organization')),
            ],
        ),
    ]
