# Generated by Django 5.1 on 2026-02-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_location_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
    ]
