# Generated by Django 5.1 on 2026-02-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contractor_fields'),
        ('users', '0002_customuser_full_name_alter_customuser_organization'),
    ]

    operations = [
    ]
