# Generated by Django 5.1 on 2026-02-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_migrate_role_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('safety_manager', 'Safety Manager'), ('action_owner', 'Action Owner'), ('observer', 'Observer'), ('contractor', 'Contractor')], default='observer', max_length=20),
        ),
    ]
