# Generated by Django 5.1 on 2026-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
