# Generated by Django 5.1 on 2026-02-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subscription_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_observations', models.IntegerField(blank=True, null=True)),
                ('max_users', models.IntegerField(blank=True, null=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan'),
        ),
    ]
