# Generated by Django 5.1 on 2026-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contractorinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG, JPG or WebP. Max 2 MB. Recommended: square or landscape, min 200×200 px.', null=True, upload_to='org_logos/'),
        ),
    ]
