# Generated by Django 5.1 on 2026-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_demorequest_status_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='role',
            field=models.CharField(choices=[('observer', 'Observer'), ('action_owner', 'Action Owner'), ('manager', 'Manager'), ('safety_manager', 'Safety Manager')], max_length=20),
        ),
    ]
