# Generated by Django 5.1 on 2026-02-22 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Safety Manager / Officer who approves the permit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permit',
            name='area_barricaded',
            field=models.BooleanField(default=False, verbose_name='Area barricaded / signed'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='attachment',
            field=models.FileField(blank=True, help_text='Risk assessment, method statement, or drawing (PDF/image).', null=True, upload_to='permits/attachments/'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='contractor_name',
            field=models.CharField(blank=True, help_text='Contractor / vendor name (if external).', max_length=255),
        ),
        migrations.AlterField(
            model_name='permit',
            name='description',
            field=models.TextField(help_text='Describe the work to be done in detail.'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='emergency_procedure',
            field=models.TextField(blank=True, help_text='Emergency response procedure specific to this work.'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='equipment_inspected',
            field=models.BooleanField(default=False, verbose_name='Equipment / tools inspected'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='gas_test_done',
            field=models.BooleanField(default=False, help_text='Required for hot work and confined space.', verbose_name='Gas / atmosphere test done'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='gas_test_result',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gas test result (e.g. O2 %, LEL %)'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='hazards_identified',
            field=models.TextField(help_text='List all foreseeable hazards for this work.'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='isolation_details',
            field=models.TextField(blank=True, help_text='Describe isolation / LOTO procedure if required.'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='isolation_required',
            field=models.BooleanField(default=False, help_text='Does this work require energy isolation / LOTO?'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='ppe_required',
            field=models.TextField(blank=True, help_text='Personal Protective Equipment required (e.g. helmet, harness, gloves).'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='requestor',
            field=models.ForeignKey(help_text='Person requesting the permit.', on_delete=django.db.models.deletion.PROTECT, related_name='permits_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permit',
            name='risk_controls',
            field=models.TextField(help_text='Controls / precautions to mitigate each hazard.'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='site_restored',
            field=models.BooleanField(default=False, verbose_name='Site cleaned & restored after work'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='toolbox_talk_done',
            field=models.BooleanField(default=False, verbose_name='Toolbox talk conducted'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='work_area',
            field=models.CharField(blank=True, help_text='Specific area / equipment tag where work will take place.', max_length=255),
        ),
        migrations.AlterField(
            model_name='permit',
            name='workers_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of workers involved.'),
        ),
    ]
