# Generated by Django 5.1 on 2026-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_alter_correctiveaction_source_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiveaction',
            name='source_module',
            field=models.CharField(choices=[('hira', 'HIRA Hazard'), ('observation', 'Observation'), ('compliance', 'Legal Compliance'), ('incident', 'Incident'), ('inspection', 'Inspection Finding'), ('manual', 'Manual')], default='manual', max_length=15),
        ),
    ]
