# Generated by Django 5.1 on 2026-04-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0002_alter_correctiveaction_source_module'),
        ('core', '0008_demorequest_status_notes'),
        ('observations', '0003_alter_location_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('workplace_safety', 'Workplace Safety'), ('fire_safety', 'Fire Safety'), ('equipment', 'Equipment / Machinery'), ('electrical', 'Electrical Safety'), ('environmental', 'Environmental'), ('general', 'General')], default='general', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_templates', to='core.organization')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location_text', models.CharField(blank=True, max_length=200)),
                ('scheduled_date', models.DateField()),
                ('conducted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='scheduled', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='observations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='inspections.inspectiontemplate')),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='inspections.inspectiontemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('is_critical', models.BooleanField(default=False, help_text='Critical items that fail will auto-raise a corrective action.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.templatesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], default='na', max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inspections.inspection')),
                ('raised_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_findings', to='actions.correctiveaction')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='inspections.inspectionitem')),
            ],
            options={
                'ordering': ['template_item__section__order', 'template_item__order'],
                'unique_together': {('inspection', 'template_item')},
            },
        ),
    ]
